<?php

// ----------------------------------------------------------
// Module exportation dfsi
// Amael Hervoche
// 21/01/2014
// ----------------------------------------------------------

// if( !defined("_DFSIEXPORT_MODULE_NAME") ) { define( "_DFSIEXPORT_MODULE_NAME" , "dfsiexport" ); }                 // nom du module
// if( !defined("_DFSI_INCLUDE_EXTENSION") ) { define( "_DFSI_INCLUDE_EXTENSION" , "inc" ); }      		// extension pour les fichiers include php

module_load_include( _DFSI_INCLUDE_EXTENSION , "dfsiexport" , "dfsiexport.define");
module_load_include( _DFSI_INCLUDE_EXTENSION , "dfsi" , "dfsi.define");
module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSIEXPORT_MODULE_NAME , "dfsiexport.permissions");
module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSIEXPORT_MODULE_NAME , "dfsiexport.menu");
module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSIEXPORT_MODULE_NAME , "dfsiexport.form");




