<?php

// ------------------------------------------------
// dfsiexport.install
// Amael Hervoche
// 21/01/2014
// ------------------------------------------------

// if( !defined("_DFSIEXPORT_MODULE_NAME") ) { define( "_DFSIEXPORT_MODULE_NAME" , "dfsiexport" ); }                 // nom du module
// if( !defined("_DFSI_INCLUDE_EXTENSION") ) { define( "_DFSI_INCLUDE_EXTENSION" , "inc" ); }      		// extension pour les fichiers include php

// module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSIEXPORT_MODULE_NAME , "dfsiexport.define");
// module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSI_MODULE_NAME , "dfsi.define");


// --------------------------------------------------
// Hook_install
// --------------------------------------------------
// --------------------------------------------------
// Fonction d'installation du module
// --------------------------------------------------
function dfsiexport_install()
{
	// Appel de la fonction de création des variables
	dfsiexport_Create_variables();
}

// --------------------------------------------------
// Hook_uninstall
// --------------------------------------------------
// --------------------------------------------------
// Fonction de desinstallation du module
// --------------------------------------------------
function dfsiexport_uninstall()
{
	// Appel de la fonction de suppression des variables
	dfsiexport_Delete_variables();
}

// --------------------------------------------------
// Hook_schema
// --------------------------------------------------
// --------------------------------------------------
// Fonction de mise en place des tables du module
// --------------------------------------------------
function dfsiexport_schema()
{

}

// --------------------------------------------------
// suppression des variables
// --------------------------------------------------
function dfsiexport_Delete_variables()
{
    db_query("DELETE FROM {variable} WHERE name LIKE 'dfsiexport_%'");
}


// --------------------------------------------------
// creation des variables par defaut pour les statuts
// --------------------------------------------------
function dfsiexport_Create_variables()
{
    variable_set('dfsiexport_Preferred_ExportMode', 1 );
    variable_set('dfsiexport_choixExport', array(1));
}