<?php

// ------------------------------------------------
// @(#) dfsiexport.define.inc
// @(#) (c) Amael Hervoche
// @(#) 23/01/2014
// ------------------------------------------------

if( !defined("_DFSIEXPORT_MODULE_NAME") ) { define( "_DFSIEXPORT_MODULE_NAME" , "dfsiexport" ); }		// nom du module
if( !defined("_DFSIEXPORT_MODE_EXPORT_CSV") ) { define( "_DFSIEXPORT_MODE_EXPORT_CSV" , 1 ); }		// export Csv
if( !defined("_DFSIEXPORT_MODE_EXPORT_XML") ) { define( "_DFSIEXPORT_MODE_EXPORT_XML" , 2 ); }		// export Xml

