<?php

// ------------------------------------------------
// @(#) dfsiexport.api.inc
// @(#) entries point for DFSI
// @(#) (c) Amael Hervoche
// @(#) 24/01/2014
// ------------------------------------------------

//importation dfsiexport.define.inc pour prendre en compte les differentes variables/constantes
// module_load_include( _INCLUDE_EXTENSION , _MODULE_NAME , "dfsiexport.define");

