<?php

// ------------------------------------------------
// @(#) dfsiexport.define.inc
// @(#) (c) Amael Hervoche
// @(#) 23/01/2014
// ------------------------------------------------

if( !defined("DFSIEXPORT_MODULE_NAME") ) { define( "DFSIEXPORT_MODULE_NAME" , "dfsiexport" ); }					// nom du module
if( !defined("DFSIEXPORT_INCLUDE_EXTENSION") ) { define( "DFSIEXPORT_INCLUDE_EXTENSION" , "inc" ); }            // extension pour les fichiers include php
